<a href="https://colab.research.google.com/github/OYOO-DA/pytorch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment



In [8]:
import torch
import numpy as np

In [9]:
a=torch.tensor([40,60,90])
b=torch.tensor([40,50,70])

In [10]:
#adition
a+b

tensor([ 80, 110, 160])

In [11]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [12]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [13]:
#using addition function
torch.add(a,b)

tensor([ 80, 110, 160])

In [14]:
#sub funtion
torch.sub(a,b)

tensor([ 0, 10, 20])

In [15]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [17]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [18]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [19]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [20]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [21]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [22]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [23]:
#remainde
a%b

tensor([ 0, 10, 20])

In [24]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [25]:
torch.pow(a,b )

tensor([0, 0, 0])

In [26]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [27]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [28]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [29]:
tensor_a

tensor([1, 2, 3, 4])

In [30]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [31]:
tensor_a

tensor([ 6,  8, 10, 12])