<a href="https://colab.research.google.com/github/OYOO-DA/pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.







In [1]:
import torch
import numpy as np

# **LISTS**


In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [3]:
np1 = np.random.rand(3,4)
np1


array([[0.32149997, 0.15071874, 0.49447796, 0.53273388],
       [0.04189586, 0.87887658, 0.86267252, 0.66505898],
       [0.84871773, 0.12036223, 0.48798796, 0.45695185]])

In [ ]:
np1.dtype


dtype('float64')

# **TENSORS**

In [4]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.2409,  0.7856, -0.3135,  0.8637],
        [ 0.3842,  0.2454, -0.8048,  0.7118],
        [-1.7472,  1.3009,  1.0149,  0.2621]])

In [5]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3215, 0.1507, 0.4945, 0.5327],
        [0.0419, 0.8789, 0.8627, 0.6651],
        [0.8487, 0.1204, 0.4880, 0.4570]], dtype=torch.float64)